---
- name: Destroy libvirt VMs
  hosts: libvirt_hosts
  become: true
  gather_facts: false
  
  vars:
    vm_config: "{{ hostvars[target_vm] }}"
    
  tasks:
    - name: Check if VM exists
      community.libvirt.virt:
        command: status
        name: "{{ vm_config.vm_name }}"
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      register: vm_status
      ignore_errors: true
      tags: check

    - name: Stop VM if running
      community.libvirt.virt:
        name: "{{ vm_config.vm_name }}"
        state: shutdown
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      when: vm_status is succeeded and vm_status.status == 'running'
      ignore_errors: true
      tags: stop

    - name: Wait for graceful shutdown
      wait_for:
        timeout: 10
      when: vm_status is succeeded and vm_status.status == 'running'
      delegate_to: localhost
      tags: stop

    - name: Force destroy VM if still running
      community.libvirt.virt:
        name: "{{ vm_config.vm_name }}"
        state: destroyed
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      when: vm_status is succeeded
      ignore_errors: true
      tags: destroy

    - name: Undefine VM
      community.libvirt.virt:
        command: undefine
        name: "{{ vm_config.vm_name }}"
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      when: vm_status is succeeded
      ignore_errors: true
      tags: undefine

    - name: Remove VM disk
      file:
        path: "{{ base_image_path }}/{{ vm_config.vm_name }}.qcow2"
        state: absent
      tags: cleanup

    - name: Remove cloud-init ISO
      file:
        path: "{{ base_image_path }}/{{ vm_config.vm_name }}-cloud-init.iso"
        state: absent
      tags: cleanup

    - name: Remove VM XML configuration
      file:
        path: "/tmp/{{ vm_config.vm_name }}.xml"
        state: absent
      tags: cleanup

    - name: Remove base image (only when explicitly requested)
      file:
        path: "{{ base_image_path }}/{{ base_image_name }}"
        state: absent
      tags: cleanup

    - name: Display destruction status
      pause:
        echo: false
        seconds: 1
        prompt: |
          VM '{{ vm_config.vm_name }}' has been destroyed and cleaned up.
      tags: info
      
    - name: Display base image cleanup info
      pause:
        echo: false
        seconds: 1
        prompt: |
          Base image '{{ base_image_name }}' was also removed.
      when: cleanup_base_image | default(false) | bool
      tags: info
