---
all:
  children:
    libvirt_hosts:
      hosts:
        localhost:
          ansible_connection: local
          libvirt_uri: "qemu:///system"
    
    vms:
      hosts:
        # Legacy VM configurations (for reference)
        ubuntu-dev:
          vm_name: "ubuntu-dev"
          vm_hostname: "ubuntu-dev"
          vm_memory: 4096
          vm_vcpus: 2
          vm_disk_size: "40G"
          vm_network: "default"
          vm_mac_address: "52:54:00:12:34:10"
          vm_os_variant: "ubuntu24.04"
          vm_autostart: false
          gpu_passthrough: false
          # Deployment-specific cloud-init settings
          vm_static_ip: "192.168.122.10"
          vm_gateway: "192.168.122.1"
          vm_dns: ["192.168.122.1", "8.8.8.8"]
          vm_packages: []
          # Docker Engine installation
          install_docker: true
          # Custom deb packages to install
          custom_packages:
            - url: "https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-amd64.deb"
              name: "bazelisk-amd64.deb"
            - url: "https://github.com/fastfetch-cli/fastfetch/releases/download/2.53.0/fastfetch-linux-amd64.deb"
              name: "fastfetch-linux-amd64.deb"
          # Post-installation script (optional)
          post_install_script: "scripts/post-install.sh"
          # Shared folders between host and VM (virtiofs)
          shared_folders:
            - source: "/home/liuyaqiu/code"
              target: "/home/vagrant/shared-folders/code"
              tag: "code"
          # Example:
          # shared_folders:
          #   - source: "/home/user/projects"
          #     target: "/mnt/projects"
          #     tag: "projects"

        # GPU passthrough VMs (disabled by default, see GPU-PASSTHROUGH-AMD.md)
        ubuntu-gpu:
          vm_name: "ubuntu-gpu"
          vm_hostname: "ubuntu-gpu"
          vm_memory: 8192
          vm_vcpus: 4
          vm_disk_size: "80G"
          vm_network: "default"
          vm_mac_address: "52:54:00:12:34:11"
          vm_os_variant: "ubuntu24.04"
          vm_autostart: false
          # NVIDIA RTX A6000 GPU passthrough (uncomment when needed)
          gpu_passthrough: true # Change to true when GPU is configured
          gpu_device_id: "0000:01:00.0"
          vm_static_ip: "192.168.122.11"
          vm_gateway: "192.168.122.1"
          vm_dns: ["192.168.122.1", "8.8.8.8"]
          vm_packages: []
          # NVIDIA driver and CUDA installation
          install_nvidia: true
          cuda_version: "13.0"
          # Docker Engine installation
          install_docker: true
          # Custom deb packages to install
          custom_packages:
            - url: "https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-amd64.deb"
              name: "bazelisk-amd64.deb"
            - url: "https://github.com/fastfetch-cli/fastfetch/releases/download/2.53.0/fastfetch-linux-amd64.deb"
              name: "fastfetch-linux-amd64.deb"
          # Post-installation script (optional)
          post_install_script: "scripts/post-install.sh"
          # Shared folders between host and VM (virtiofs)
          shared_folders:
            - source: "/home/liuyaqiu/code"
              target: "/home/vagrant/shared-folders/code"
              tag: "code"
          # Example:
          # shared_folders:
          #   - source: "/home/user/projects"
          #     target: "/mnt/projects"
          #     tag: "projects"
