---
- name: List and get information about libvirt VMs
  hosts: libvirt_hosts
  become: true
  gather_facts: false
  
  tasks:
    - name: Get list of all VMs
      community.libvirt.virt:
        command: list_vms
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      register: all_vms
      tags: list

    - name: Get running VMs
      community.libvirt.virt:
        command: list_vms
        state: running
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      register: running_vms
      tags: list

    - name: Get VM info for each VM
      community.libvirt.virt:
        command: info
        name: "{{ item }}"
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      register: vm_details
      loop: "{{ all_vms.list_vms }}"
      when: all_vms.list_vms | length > 0
      tags: details

    - name: Display VM summary
      pause:
        echo: false
        seconds: 1
        prompt: |
          Total VMs: {{ all_vms.list_vms | length }}
          Running VMs: {{ running_vms.list_vms | length }}

          VM Details:
          {% for vm_item_result in vm_details.results -%}
          {% set vm_data = vm_item_result[vm_item_result.item] -%}
          - Name: {{ vm_item_result.item }}
            State: {{ vm_data.state | default('N/A') }}
            Memory: {{ (vm_data.memory | int / 1024 / 1024) | round(2) | default('N/A') }} GB
            VCPUs: {{ vm_data.nrVirtCpu | default('N/A') }}
            Autostart: {{ vm_data.autostart | default('N/A') }}
            CPU Time: {{ (vm_data.cpuTime | int / 1000000000) | round(2) | default('N/A') }} seconds

          {% endfor %}
      when: all_vms.list_vms | length > 0
      tags: summary

    - name: Display message when no VMs exist
      pause:
        echo: false
        seconds: 1
        prompt: |
          No VMs found in libvirt.
      when: all_vms.list_vms | length == 0
      tags: summary

    - name: Get network information
      community.libvirt.virt_net:
        command: list_nets
        uri: "{{ libvirt_uri | default('qemu:///system') }}"
      register: networks
      tags: network

    - name: Display network information
      pause:
        echo: false
        seconds: 1
        prompt: |
          Available networks:
          {% for net in networks.list_nets %}
          - {{ net }}
          {% endfor %}
      tags: network
